version: '3.5'

volumes:
  redis-volume:
    name: internal-redis-db

services:
  api:
    container_name: ${PROJECT_NAME}-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: [.env]
    ports:
      - 3000:${PORT:-3000}
    depends_on:
      - redis

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:7-alpine
    restart: unless-stopped
    env_file: [.env]
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data
